-- MySQL Script generated by MySQL Workbench
-- Tue Oct 21 16:41:01 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gestorpincadb2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestorpincadb2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestorpincadb2` DEFAULT CHARACTER SET utf8mb4 ;
USE `gestorpincadb2` ;

-- -----------------------------------------------------
-- Table `gestorpincadb2`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`empresa` (
  `id_empresa` INT(11) NOT NULL,
  `nit` VARCHAR(11) NULL DEFAULT NULL,
  `razon_social` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `pagina_web` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_empresa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`instalaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`instalaciones` (
  `id_instalaciones` INT(11) NOT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `ciudad` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(45) NULL DEFAULT NULL,
  `id_empresa` INT(11) NOT NULL,
  PRIMARY KEY (`id_instalaciones`),
  INDEX `fk_instalaciones_empresa_idx` (`id_empresa` ASC) ,
  CONSTRAINT `fk_instalaciones_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `gestorpincadb2`.`empresa` (`id_empresa`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`bodegas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`bodegas` (
  `id_bodegas` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `estado` TINYINT(4) NULL DEFAULT NULL COMMENT '0 inactiva 1 activa',
  `instalaciones_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_bodegas`),
  INDEX `fk_bodegas_instalaciones1_idx` (`instalaciones_id` ASC) ,
  CONSTRAINT `fk_bodegas_instalaciones1`
    FOREIGN KEY (`instalaciones_id`)
    REFERENCES `gestorpincadb2`.`instalaciones` (`id_instalaciones`)
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`categoria` (
  `id_categoria` INT(11) NOT NULL,
  `nombre` VARCHAR(13) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`movimiento_inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`movimiento_inventario` (
  `id_movimiento_inventario` INT(11) NOT NULL,
  `tipo_movimiento` VARCHAR(6) NULL DEFAULT NULL,
  `cantidad` DECIMAL(10,2) NULL DEFAULT NULL,
  `fecha_movimiento` VARCHAR(0) NULL DEFAULT NULL,
  `descripcion` VARCHAR(32) NULL DEFAULT NULL,
  `referencia_tipo` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id_movimiento_inventario`),
  UNIQUE INDEX `id_movimiento_inventario_UNIQUE` (`id_movimiento_inventario` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`facturas` (
  `id_facturas` INT(11) NOT NULL,
  `numero` VARCHAR(6) NULL DEFAULT NULL,
  `cliente_id` INT(11) NULL DEFAULT NULL,
  `fecha_emision` VARCHAR(0) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  `estado` VARCHAR(9) NULL DEFAULT NULL,
  `subtotal` DECIMAL(10,2) NULL DEFAULT NULL,
  `impuestos` DECIMAL(10,2) NULL DEFAULT NULL,
  `retencion` DECIMAL(10,2) NULL DEFAULT NULL,
  `movimiento_inventario_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_facturas`),
  UNIQUE INDEX `id_facturas_UNIQUE` (`id_facturas` ASC) ,
  INDEX `fk_facturas_movimientos_inventario1_idx` (`movimiento_inventario_id` ASC) ,
  CONSTRAINT `fk_facturas_movimientos_inventario1`
    FOREIGN KEY (`movimiento_inventario_id`)
    REFERENCES `gestorpincadb2`.`movimiento_inventario` (`id_movimiento_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`clientes` (
  `id_clientes` INT(11) NOT NULL,
  `nombre_encargado` VARCHAR(13) NULL DEFAULT NULL,
  `nombre_empresa` VARCHAR(11) NULL DEFAULT NULL,
  `numero_documento` BIGINT(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(14) NULL DEFAULT NULL,
  `telefono` BIGINT(20) NULL DEFAULT NULL,
  `email` VARCHAR(29) NULL DEFAULT NULL,
  `facturas_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_clientes`),
  INDEX `fk_clientes_facturas1_idx` (`facturas_id` ASC) ,
  CONSTRAINT `fk_clientes_facturas1`
    FOREIGN KEY (`facturas_id`)
    REFERENCES `gestorpincadb2`.`facturas` (`id_facturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`unidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`unidad` (
  `id_unidad` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `estados` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id_unidad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`item_general`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`item_general` (
  `id_item_general` INT(11) NOT NULL,
  `nombre` VARCHAR(36) NULL DEFAULT NULL,
  `codigo` VARCHAR(6) NULL DEFAULT NULL,
  `tipo` TINYINT(4) NULL DEFAULT NULL COMMENT '0 productos\\n1 materia prima\\n2 Insumos',
  `categoria_id` INT(11) NULL DEFAULT NULL,
  `viscosidad` VARCHAR(10) NULL DEFAULT NULL,
  `p_g` VARCHAR(14) NULL DEFAULT NULL,
  `color` VARCHAR(3) NULL DEFAULT NULL,
  `brillo_60` VARCHAR(6) NULL DEFAULT NULL,
  `secado` VARCHAR(8) NULL DEFAULT NULL,
  `cubrimiento` VARCHAR(9) NULL DEFAULT NULL,
  `molienda` VARCHAR(5) NULL DEFAULT NULL,
  `ph` VARCHAR(1) NULL DEFAULT NULL,
  `poder_tintoreo` VARCHAR(13) NULL DEFAULT NULL,
  `volumen` VARCHAR(6) NULL DEFAULT NULL,
  `cantidad` DECIMAL(10,2) NULL DEFAULT NULL,
  `unidad_id` INT(11) NULL DEFAULT NULL,
  `costo_produccion` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id_item_general`),
  UNIQUE INDEX `id_item_general_UNIQUE` (`id_item_general` ASC) ,
  INDEX `fk_item_general_categoria1_idx` (`categoria_id` ASC) ,
  INDEX `fk_item_general_unidad_id_idx` (`unidad_id` ASC) ,
  CONSTRAINT `fk_item_general_categoria1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `gestorpincadb2`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_general_unidad_id`
    FOREIGN KEY (`unidad_id`)
    REFERENCES `gestorpincadb2`.`unidad` (`id_unidad`)
    ON DELETE SET NULL
    ON UPDATE SET NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`costos_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`costos_item` (
  `id` INT(11) NOT NULL,
  `item_general_id` INT(11) NOT NULL,
  `costo_unitario` INT(11) NULL DEFAULT NULL,
  `costo_mp_galon` INT(11) NULL DEFAULT NULL,
  `periodo` VARCHAR(7) NULL DEFAULT NULL,
  `metodo_calculo` VARCHAR(6) NULL DEFAULT NULL,
  `fecha_calculo` DATE NULL DEFAULT NULL,
  `costo_mp_kg` INT(11) NULL DEFAULT NULL,
  `envase` INT(11) NULL DEFAULT NULL,
  `etiqueta` INT(11) NULL DEFAULT NULL,
  `bandeja` INT(11) NULL DEFAULT NULL,
  `plastico` INT(11) NULL DEFAULT NULL,
  `costo_total` INT(11) NULL DEFAULT NULL,
  `volumen` DECIMAL(10,0) NULL DEFAULT NULL,
  `precio_venta` INT(11) NULL DEFAULT NULL,
  `cantidad_total` INT(11) NULL DEFAULT NULL,
  `costo_mod` INT(11) NULL DEFAULT NULL COMMENT '0  inactivo\n1 activo',
  `estado` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `item_general_id` (`item_general_id` ASC) ,
  CONSTRAINT `costos_item_ibfk_1`
    FOREIGN KEY (`item_general_id`)
    REFERENCES `gestorpincadb2`.`item_general` (`id_item_general`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`preparaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`preparaciones` (
  `id_preparaciones` INT(11) NOT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `fecha_inicio` DATE NULL DEFAULT NULL,
  `fecha_fin` DATE NULL DEFAULT NULL,
  `cantidad` DECIMAL(10,2) NULL DEFAULT NULL,
  `item_general_id` INT(11) NULL DEFAULT NULL,
  `unidad_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_preparaciones`),
  INDEX `fk_preparaciones_item_general1_idx` (`item_general_id` ASC) ,
  INDEX `fk_preparaciones_unidad1_idx` (`unidad_id` ASC) ,
  CONSTRAINT `fk_preparaciones_item_general1`
    FOREIGN KEY (`item_general_id`)
    REFERENCES `gestorpincadb2`.`item_general` (`id_item_general`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preparaciones_unidad1`
    FOREIGN KEY (`unidad_id`)
    REFERENCES `gestorpincadb2`.`unidad` (`id_unidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`costos_produccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`costos_produccion` (
  `id` INT(11) NOT NULL,
  `costo_unitario` MEDIUMINT(9) NULL DEFAULT NULL,
  `costo_mp_galon` TINYINT(4) NULL DEFAULT NULL,
  `periodo` VARCHAR(7) NULL DEFAULT NULL,
  `metodo_calculo` VARCHAR(6) NULL DEFAULT NULL,
  `fecha_calculo` VARCHAR(0) NULL DEFAULT NULL,
  `costo_mp_kg` TINYINT(4) NULL DEFAULT NULL,
  `envase` SMALLINT(6) NULL DEFAULT NULL,
  `etiqueta` SMALLINT(6) NULL DEFAULT NULL,
  `bandeja` SMALLINT(6) NULL DEFAULT NULL,
  `plastico` SMALLINT(6) NULL DEFAULT NULL,
  `costo_total` TINYINT(4) NULL DEFAULT NULL,
  `volumen` VARCHAR(5) NULL DEFAULT NULL,
  `precio_venta` TINYINT(4) NULL DEFAULT NULL,
  `cantidad_total` TINYINT(4) NULL DEFAULT NULL,
  `costo_mod` SMALLINT(6) NULL DEFAULT NULL,
  `preparaciones_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) ,
  INDEX `fk_costos_produccion_preparaciones1_idx` (`preparaciones_id` ASC) ,
  CONSTRAINT `fk_costos_produccion_preparaciones`
    FOREIGN KEY (`preparaciones_id`)
    REFERENCES `gestorpincadb2`.`preparaciones` (`id_preparaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`detalle_facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`detalle_facturas` (
  `id_detalle_facturas` INT(11) NOT NULL,
  `cantidad` TINYINT(4) NULL DEFAULT NULL,
  `precio_unitario` DECIMAL(7,1) NULL DEFAULT NULL,
  `subtotal` DECIMAL(7,1) NULL DEFAULT NULL,
  `facturas_id` INT(11) NULL DEFAULT NULL,
  `item_general_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_detalle_facturas`),
  UNIQUE INDEX `id_detalle_facturas_UNIQUE` (`id_detalle_facturas` ASC) ,
  INDEX `fk_detalle_facturas_facturas1_idx` (`facturas_id` ASC) ,
  INDEX `fk_detalle_facturas_item_general1_idx` (`item_general_id` ASC) ,
  CONSTRAINT `fk_detalle_facturas_facturas1`
    FOREIGN KEY (`facturas_id`)
    REFERENCES `gestorpincadb2`.`facturas` (`id_facturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_facturas_item_general1`
    FOREIGN KEY (`item_general_id`)
    REFERENCES `gestorpincadb2`.`item_general` (`id_item_general`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`formulaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`formulaciones` (
  `id_formulaciones` INT(11) NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `descripcion` VARCHAR(500) NULL DEFAULT NULL,
  `estado` TINYINT(4) NULL DEFAULT NULL COMMENT '0 inactiva\\n1 activa',
  `defecto` TINYINT(4) NULL DEFAULT 0 COMMENT '1 por defecto',
  `item_general_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_formulaciones`),
  UNIQUE INDEX `id_formulaciones_UNIQUE` (`id_formulaciones` ASC) ,
  INDEX `fk_formulaciones_item_general1_idx` (`item_general_id` ASC) ,
  CONSTRAINT `fk_formulaciones_item_general1`
    FOREIGN KEY (`item_general_id`)
    REFERENCES `gestorpincadb2`.`item_general` (`id_item_general`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`inventario` (
  `id_inventario` INT(11) NOT NULL,
  `cantidad` DECIMAL(5,2) NULL DEFAULT NULL,
  `fecha_update` VARCHAR(0) NULL DEFAULT NULL,
  `apartada` TINYINT(4) NULL DEFAULT NULL,
  `item_general_id` INT(11) NOT NULL,
  `estado` TINYINT(5) NULL DEFAULT NULL COMMENT '0 disponible\\r\\n1 No disponible',
  `movimiento_inventario_id` INT(11) NULL DEFAULT NULL,
  `tipo` TINYINT NULL COMMENT '1 ingreso\n2 egreso',
  `bodegas_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_inventario`),
  INDEX `fk_inventario_item_general1_idx` (`item_general_id` ASC) ,
  INDEX `fk_inventario_movimientos_inventario1_idx` (`movimiento_inventario_id` ASC) ,
  INDEX `fk_inventario_bodega` (`bodegas_id` ASC) ,
  CONSTRAINT `fk_inventario_bodega`
    FOREIGN KEY (`bodegas_id`)
    REFERENCES `gestorpincadb2`.`bodegas` (`id_bodegas`),
  CONSTRAINT `fk_inventario_item_general1`
    FOREIGN KEY (`item_general_id`)
    REFERENCES `gestorpincadb2`.`item_general` (`id_item_general`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventario_movimientos_inventario1`
    FOREIGN KEY (`movimiento_inventario_id`)
    REFERENCES `gestorpincadb2`.`movimiento_inventario` (`id_movimiento_inventario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`item_general_formulaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`item_general_formulaciones` (
  `id_item_general_formulaciones` INT(11) NOT NULL,
  `formulaciones_id` INT(11) NOT NULL,
  `cantidad` DECIMAL(10,2) NULL DEFAULT NULL,
  `porcentaje` INT(11) NULL DEFAULT NULL,
  `item_general_id` INT(11) NOT NULL,
  PRIMARY KEY (`id_item_general_formulaciones`),
  INDEX `fk_item_especifico_has_formulaciones_formulaciones1_idx` (`formulaciones_id` ASC) ,
  INDEX `fk_item_especifico_formulaciones_item_general1_idx` (`item_general_id` ASC) ,
  CONSTRAINT `fk_item_general_has_formulaciones_formulaciones1`
    FOREIGN KEY (`formulaciones_id`)
    REFERENCES `gestorpincadb2`.`formulaciones` (`id_formulaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_general_formulaciones_item_general1`
    FOREIGN KEY (`item_general_id`)
    REFERENCES `gestorpincadb2`.`item_general` (`id_item_general`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`proveedor` (
  `id_proveedor` INT(11) NOT NULL,
  `nombre_encargado` VARCHAR(16) NULL DEFAULT NULL,
  `nombre_empresa` VARCHAR(27) NULL DEFAULT NULL,
  `numero_documento` VARCHAR(11) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `telefono` VARCHAR(14) NULL DEFAULT NULL,
  `email` VARCHAR(34) NULL DEFAULT NULL,
  PRIMARY KEY (`id_proveedor`),
  UNIQUE INDEX `id_proveedor_UNIQUE` (`id_proveedor` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`item_proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`item_proveedor` (
  `id_item_proveedor` INT(11) NOT NULL,
  `nombre` VARCHAR(55) NULL DEFAULT NULL,
  `codigo` VARCHAR(10) NULL DEFAULT NULL,
  `tipo` VARCHAR(13) NULL DEFAULT NULL,
  `unidad_empaque` VARCHAR(13) NULL DEFAULT NULL,
  `precio_unitario` MEDIUMINT(9) NULL DEFAULT NULL,
  `precio_con_iva` DECIMAL(7,1) NULL DEFAULT NULL,
  `disponible` TINYINT(4) NULL DEFAULT NULL,
  `descripcion` VARCHAR(55) NULL DEFAULT NULL,
  `proveedor_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_item_proveedor`),
  UNIQUE INDEX `id_item_proveedor_UNIQUE` (`id_item_proveedor` ASC) ,
  INDEX `fk_item_proveedor_proveedores1_idx` (`proveedor_id` ASC) ,
  CONSTRAINT `fk_item_proveedor_proveedores1`
    FOREIGN KEY (`proveedor_id`)
    REFERENCES `gestorpincadb2`.`proveedor` (`id_proveedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`pagos_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`pagos_cliente` (
  `id_pagos_cliente` INT(11) NOT NULL,
  `fecha_pago` VARCHAR(0) NULL DEFAULT NULL,
  `monto` DECIMAL(7,1) NULL DEFAULT NULL,
  `metodo_pago` VARCHAR(8) NULL DEFAULT NULL,
  `observaciones` VARCHAR(0) NULL DEFAULT NULL,
  `clientes_id` INT(11) NULL DEFAULT NULL,
  `facturas_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_pagos_cliente`),
  UNIQUE INDEX `id_pagos_cliente_UNIQUE` (`id_pagos_cliente` ASC) ,
  INDEX `fk_pagos_cliente_clientes1_idx` (`clientes_id` ASC) ,
  INDEX `fk_pagos_cliente_facturas1_idx` (`facturas_id` ASC) ,
  CONSTRAINT `fk_pagos_cliente_clientes1`
    FOREIGN KEY (`clientes_id`)
    REFERENCES `gestorpincadb2`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagos_cliente_facturas1`
    FOREIGN KEY (`facturas_id`)
    REFERENCES `gestorpincadb2`.`facturas` (`id_facturas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
ROW_FORMAT = DYNAMIC;


-- -----------------------------------------------------
-- Table `gestorpincadb2`.`preparaciones_has_item_general`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorpincadb2`.`preparaciones_has_item_general` (
  `preparaciones_id_preparaciones` INT(11) NOT NULL,
  `item_general_id_item_general` INT(11) NOT NULL,
  `cantidad` DECIMAL(10,2) NULL,
  `porcentajes` INT NULL,
  PRIMARY KEY (`preparaciones_id_preparaciones`, `item_general_id_item_general`),
  INDEX `fk_preparaciones_has_item_general_item_general1_idx` (`item_general_id_item_general` ASC) ,
  INDEX `fk_preparaciones_has_item_general_preparaciones1_idx` (`preparaciones_id_preparaciones` ASC) ,
  CONSTRAINT `fk_preparaciones_has_item_general_preparaciones1`
    FOREIGN KEY (`preparaciones_id_preparaciones`)
    REFERENCES `gestorpincadb2`.`preparaciones` (`id_preparaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_preparaciones_has_item_general_item_general1`
    FOREIGN KEY (`item_general_id_item_general`)
    REFERENCES `gestorpincadb2`.`item_general` (`id_item_general`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
